### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Pirozek** [jcalfee/trez#2]
Hey, I am trying to use your library but after installing and running `trez -?` I get `ReferenceError: regeneratorRuntime is not defined` at line 297 i `lib/device.js`. Any idea what I am doing wrong?

**Comment by jcalfee** [comment]
The dependencies are not well maintained.  If you can use another utility that would be better.  I plan to checkout trezor's command line library: trezorctl in more detail..

**Comment by jcalfee** [comment]
this is a possible work-around if you have already created trez files and can't decrypt them
:  https://github.com/trezor/python-trezor/issues/264

I'm not sure if we will have a reliable node only trez program.  The solutions so far involve installing something from trezor.

**Comment by jcalfee** [comment]
I made some upgrades for node v8 compatibility and added the babel-polyfill .. The latest version is trez@1.0.5
